language: node_js
node_js:
- '10'
install:
- npm install
script:
- npm run clean
- npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: public
  on:
    branch: master
  target_branch: gh-pages
env:
  global:
    secure: L1P3asNiZr74INln7H8lQtHj7inMsJAPXhTbw8ej//mTh/tC/vMVctcLaCQOF40JyVWS9/im7wITNIB1QGRSveC66flrZNVWWh+++Qww7o3aBDGhrgG54HuB5epiZSpPYOdzrXemZrIyMD7ivoIG+2Ams/VTB1GVWL4Ag2As0aY0ojqFPtyKpPBnDzQ1MDjg3HgT/BahdBJKSq52yVRNbTB119ZNvNtSAfR9LxWYfD4e+JHloAB88g2aqNzOo3DoVywobZ2kaxxOsGLx7lExthvrdjHQt+xL0edKNLfKaDCWCaF9jlTFGcjlaG/XUwq0DRz3c0XEj1/0daBux2QrqEBni8h7RpkFUsaAHEWY+/kpmKJcU0XXIpkoWFv7LALIObdI818KhcDwR9vsruCl0a0YGXQwu49+OJDtBOmfsSx814fx/reHxHnxVGbQugfe3kW6T1+tgbxgXvTW4lqJl93yJxuZZRzLiQSOPxlPEYMELg6w4pNxlAaYMOqgzIeK+uqqIl7pbAn5xAgaPK4b1DNlRrWImvhxSn9SzG8H9KeU+sPNq0t2hJj8CoWgXtYEQjYeXIa8PHjswGByVH8phtJkj9bGfDx0H/Ffw6YjPqXc/m8mGa1HAeFHoNYfpYJo0wR32LvX8N/uZVPMswuDn1CVglXJyNyOJLbqGlBq3eo=
