language: node_js
node_js:
- '10'
install:
- npm install
script:
- npm run clean
- npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: public
  on:
    branch: master
  target_branch: gh-pages
env:
  global:
  - secure: EVqJhaFAi2yc7moGz8slJuV5Mw5JkfIeN2nQsbuRrJydjBRsNvURTwFoxFVNyU1iyH2KkO9+aDqiXrtKRddZCSvm+zCTkxLjaHEYVbKNG+Hz+gjva9BlDDJr/r4OkM/8Uhl2Swqxsv6c8P377WzpttFoq/CwP8YDZAU0ggPx7yoLuygnobSFr8cQ8rzBu9yqy0/Er8Qw1gDdXH49J2oSIJai8LwKjppBMMstWzsX5Xu5dM61N/C6ZswTpABfpfD9BE3A2n8MBhY8USKVwVdtRZxqUydKZVGPiQ9TwVRmVnJYwmDZ3Rlph34d6aZPcsCplSU1m79CTNDhA5i0SYL5D4/OnB4bK0JDxeaz+lv+iSb0bn+5ZnyV2CZweZicAR4G06gmBD+J5pSnVw9YeXLAxjUnrDWxVvvzMslAbzvAewug6lU+RjB4pY8rj4e8tm4Kznqg0fWTt1rK3Q06Sy8C1BMySuCjp31v3XZin8QsDAsyyycJ78ccRwZYNUHVzjrqrRxhKoAmh6B7j5xTDmcNAM4AUF4FfrYRPHUC2brpYCfMrFPiqDJng6dvSzPXgb5DqkP58DtYM73A1Z7dExqcSVgbLnFI/zarNLasLVlS8362Mj2u/Wgzf8IsQWdekxU1mClLnv86iCpujah3xeELpM7M3v1aVIk9jAdLH1deIJ4=
